### ISSUE TITLE
Relax upper bound constraints to build with base 4.15

### ISSUE THREAD

**Issue by pepeiborra** [diagrams/diagrams-core#112]
The following packages need their base upper bounds relaxed:

-	active
-	diagrams-contrib
-	diagrams-core
-	diagrams-lib
-	diagrams-postscript
- diagrams-svg
-	dual-tree
-	force-layout
-	monoid-extras
-	statestack
-	svg-builder

Thank you for this beautiful stack of libraries!

**Comment by ezzieyguywuf** [comment]
`diagrams-builder` needs to be added to this list, and also needs some other upperbounds bumped as well.

**Comment by ezzieyguywuf** [comment]
For what it's worth, in gentoo i just patched the cabal files to remove the offending upper  bounds and things seemed to Just Work (tm)

**Comment by guygastineau** [comment]
Okay, thank you for the response.  I guess I will try making PRs for each of those packages in the list at the top of this issue.  I need to use this library for both linux and windows binaries, so I would prefer having it fixed up stream eventually, but I can vendor them for the time being I guess... :/

Thank you again :pray:

**Comment by ezzieyguywuf** [comment]
No problem!

I haven't personally tried it, but you may also consider using the `--allow-newer` option of cabal. See [here](https://cabal.readthedocs.io/en/3.2/nix-local-build.html#cfg-field-allow-newer) for more info.

**Comment by guygastineau** [comment]
I have messed with `allow-newer` before.  In real projects with a decent amount of dependencies it tends to break something.

**Comment by ezzieyguywuf** [comment]
It looks like you can restrict which specific dependencies you relax the bounds on though, and even how much you relax them.

Seems like a pretty reasonable way to hobble along until upstream gets their act together :-P

**Comment by guygastineau** [comment]
Oh, wow.  Somehow I didn't realize that.  I will read the docs again I guess ;)

**Comment by guygastineau** [comment]
Hmm, for some reason it seems like it ignore my `allow-newer` settings in `<project>.cabal`...  When I run with `cabal new-build --allow-newer` then it finally fixes the dependency conflicts, but including scoped allow newer settings in my cabal file doesn't work.  Do I need to do something special?  Do I need to use the flag at the cli in addition to specifying the the scoped package allow-newer settings in my cabal file?  I am just a bit confused.  I know this isn't a forum for getting help with cabal-install, but I really apprevciate any insight you have.  Thanks.

**Comment by ezzieyguywuf** [comment]
Hrm, yea I'd probably move the convo to somewhere more cabal-specific if I were you. The only thing that comes to mind is to check your cabal versions - both cabal-the-library and cabal-the-exectuable. `cabal --version` should give you both.

This seems like a generally newish feature so that could be what's causing the discrepenancy you see. Or you may have found a genuine bug.

I personally don't use cabal-the-executable when packaging in gentoo, so I'm not sure if I'll see the same issue. But I'll let you know.

**Comment by guygastineau** [comment]
I figured it out from asking Reddit.  I didn't know it needed to go into the `project.cabal`.  I was just trying to use it in my individual cabal files.  Thank you for your help.

**Comment by byorgey** [comment]
Hi all, thanks for the nudges and the helpful advice on how to get diagrams working in the meantime.  I'm definitely aware that the diagrams packages all need bounds updated, and hope to work on getting things updated soon.

**Comment by sternenseemann** [comment]
Related

* <https://github.com/diagrams/diagrams-cairo/issues/77>
* <https://github.com/diagrams/diagrams-rasterific/issues/63>

**Comment by byorgey** [comment]
I believe that all these packages have now been updated on Hackage.

**Comment by kindaro** [comment]
Thanks Brent!

**Comment by sternenseemann** [comment]
Thanks a lot of stuff has been resolved now! It seems that now all remaining diagrams packages need to be adjusted for monoid-extras 0.6 / join the 1.5 release line since in some cases these bounds fixed were combined with other breaking changes and atm not all diagrams packages seem to work together in their latest released form on hackage.

**Comment by byorgey** [comment]
Hi @sternenseemann , yes, there are still other diagrams packages that need to be updated, I am slowly working through the list.  However, I'm not sure what you mean by upper bounds fixes being combined with other breaking changes --- can you give an example?

**Comment by sternenseemann** [comment]
> Hi @sternenseemann , yes, there are still other diagrams packages that need to be updated, I am slowly working through the list. However, I'm not sure what you mean by upper bounds fixes being combined with other breaking changes --- can you give an example?

The issue mostly affects `diagrams-lib` I think (and maybe similar cases, haven't checked) where the update fixing the upper bounds problem also included adjustments for `monoid-extras` 0.6. This then forces upgrading to `diagrams-core` 1.5.0 which creates the situation with mismatched 1.4.* and 1.5.* libraries.

For nixpkgs, I have chosen to work around this by patching `diagrams-lib`, so we have the fixes for `optparse-applicative`, but not for `monoid-extras`, so it is possible to workaround this issue for now.

**Comment by byorgey** [comment]
I'm still not sure I understand.  What is the problem with being forced to upgrade to `diagrams-core-1.5` and having mismatched version numbers?  Does something actually break or do you just not like having the version numbers be different?

Once upon a time we tried to make sure that the version numbers of all the diagrams packages stayed in sync with each other.  But that was annoying and a lot of work.  In this case adjusting to some changes in dependencies required technically breaking changes in `monoid-extras` and `diagrams-core`, and I decided it was not worth it to go through and make a major version bump in all the other diagrams packages (whose APIs did not change at all) just to have the version numbers stay in sync.

**Comment by sternenseemann** [comment]
I want to keep the `diagrams` wrapper package working as well which constrains `diagrams-core` and `diagrams-lib` to 1.4.* which is the concrete problem currently. Also I don't think all packages support monoid-extras 0.6 yet, so that also creates trouble since we can't have multiple versions of that package at the same time.

By the way, what happened to the idea of a [diagrams monorepo](https://github.com/diagrams/diagrams-postscript/issues/31#issuecomment-565518799)? I can imagine that it would reduce the churn making such changes and it would also help people like me maintain an overview.

**Comment by byorgey** [comment]
I still think a diagrams monorepo would be a good idea in theory, but it sounds like a lot of work to import everything and get the CI set up and so on.
